import type { FunctionTree, FunctionNode, ModuleNode, ReverseIndex } from "./types.ts";

const HEADER = "<!-- Generated by scripts/function-tree — do not hand-edit. -->";

export type RenderedFiles = {
  // Map from relative path under docs/function-tree/ -> file body.
  [relPath: string]: string;
};

function rootSlug(root: string): string {
  return root.split("/").join("-");
}

function classificationBadge(tags: string[]): string {
  return tags.length === 0 ? "" : `\`${tags.join(", ")}\``;
}

function countEdges(m: ModuleNode): { out: number; methods: number; topLevel: number; classes: number } {
  let out = 0;
  let methods = 0;
  let topLevel = 0;
  for (const f of m.functions) {
    out += f.edges.length;
    if (f.kind === "method") methods++;
    else topLevel++;
  }
  // We don't currently emit class nodes; classes are inferred via methods.
  const classes = new Set(
    m.functions
      .filter((f) => f.kind === "method" && f.name.includes("."))
      .map((f) => f.name.split(".")[0])
  ).size;
  return { out, methods, topLevel, classes };
}

function fnHeading(f: FunctionNode): string {
  const tag = f.classification.length ? ` _(${f.classification.join(", ")})_` : "";
  return `#### \`${f.name}\` — ${f.kind}, L${f.line}${tag}`;
}

function edgeLines(f: FunctionNode, reverse: ReverseIndex): string[] {
  const lines: string[] = [];
  // Group by edge kind; mix internal + external in the same list, marking external as `[external] <pkg>`.
  const buckets: Record<"calls" | "renders" | "new" | "dynamic-import", string[]> = {
    calls: [],
    renders: [],
    new: [],
    "dynamic-import": [],
  };
  for (const e of f.edges) {
    const val = "target" in e ? `\`${e.target}\`` : `\`[external] ${e.external}\``;
    buckets[e.kind].push(val);
  }
  for (const [label, vals] of Object.entries(buckets)) {
    if (vals.length === 0) continue;
    const unique = [...new Set(vals)].sort();
    lines.push(`- ${label}: ${unique.join(", ")}`);
  }

  const reverseLabels: Array<[keyof ReverseIndex, string]> = [
    ["calls", "called by"],
    ["renders", "rendered by"],
    ["new", "instantiated by"],
    ["dynamic-import", "dynamic-imported by"],
  ];
  for (const [k, label] of reverseLabels) {
    const inbound = reverse[k][f.id];
    if (!inbound || inbound.length === 0) continue;
    lines.push(`- ${label}: ${inbound.map((id) => `\`${id}\``).join(", ")}`);
  }

  if (f.unresolved > 0) lines.push(`- unresolved: ${f.unresolved}`);
  return lines;
}

export function renderMarkdown(tree: FunctionTree): RenderedFiles {
  const out: RenderedFiles = {};
  const byRoot = new Map<string, ModuleNode[]>();
  for (const m of tree.modules) {
    if (!byRoot.has(m.root)) byRoot.set(m.root, []);
    byRoot.get(m.root)!.push(m);
  }

  out["index.md"] = renderIndex(tree, byRoot);
  out["modules.md"] = renderModules(tree);
  for (const [root, mods] of byRoot) {
    out[`${rootSlug(root)}.md`] = renderRoot(root, mods, tree.reverse);
  }
  return out;
}

function renderIndex(tree: FunctionTree, byRoot: Map<string, ModuleNode[]>): string {
  const lines: string[] = [
    HEADER,
    "",
    "# Function tree — index",
    "",
    `Generated: \`${tree.generated_at}\` · Schema: \`${tree.$schema}\``,
    "",
    "## How to use this file",
    "",
    "Before editing any function, look it up here to see what calls it. Each per-root file lists every function/method/component declared in that root with its `calls:` / `called by:` / `renders:` / `rendered by:` / `new:` / `instantiated by:` / `dynamic-import:` neighbours. \"If I change `X`, what breaks?\" → grep the per-root file for `\\`X\\``, read the inbound edges, you have your blast radius.",
    "",
    "Edges are machine-extracted from the TypeScript program — re-exports are followed to the real declaration, JSX renders count as edges, dynamic imports point at the module they pull in, and external (`node_modules/`) targets are tagged `[external] <pkg>` instead of being emitted as internal IDs. Unresolved targets (computed dispatch, untyped indexing) are counted per function rather than guessed.",
    "",
    "## This file does NOT define behavior",
    "",
    "This artifact is a derived view, not a contract. The authoritative architectural view of how the system fits together — domain boundaries, layering rules, RLS perimeter, where things should live — is `docs/engineering-handbook.md` §4. The function tree is regenerated from source via `npm run map` and verified fresh in CI via `npm run map:check`; if it disagrees with the handbook, the handbook wins for design intent and the tree is just out of date.",
    "",
    "## Roots",
    "",
    "| Root | File | Modules | Top-level fns | Classes | Methods | Edges out |",
    "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
  ];
  const roots = [...byRoot.keys()].sort();
  for (const root of roots) {
    const mods = byRoot.get(root)!;
    let totalTop = 0;
    let totalMethods = 0;
    let totalClasses = 0;
    let totalOut = 0;
    for (const m of mods) {
      const c = countEdges(m);
      totalTop += c.topLevel;
      totalMethods += c.methods;
      totalClasses += c.classes;
      totalOut += c.out;
    }
    const file = `${rootSlug(root)}.md`;
    lines.push(
      `| \`${root}\` | [\`${file}\`](./${file}) | ${mods.length} | ${totalTop} | ${totalClasses} | ${totalMethods} | ${totalOut} |`
    );
  }
  lines.push("", "## Where to read next", "", "- [`modules.md`](./modules.md) — one-liner directory of every walked module.");
  for (const root of roots) {
    const file = `${rootSlug(root)}.md`;
    lines.push(`- [\`${file}\`](./${file}) — \`${root}\` bidirectional call graph.`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderModules(tree: FunctionTree): string {
  const lines: string[] = [
    HEADER,
    "",
    "# Function tree — modules",
    "",
    "| Module | Root | Classification | Fns | Edges out |",
    "| --- | --- | --- | ---: | ---: |",
  ];
  for (const m of tree.modules) {
    const c = countEdges(m);
    lines.push(
      `| \`${m.path}\` | \`${m.root}\` | ${classificationBadge(m.classification)} | ${m.functions.length} | ${c.out} |`
    );
  }
  lines.push("");
  return lines.join("\n");
}

function renderRoot(root: string, modules: ModuleNode[], reverse: ReverseIndex): string {
  const lines: string[] = [
    HEADER,
    "",
    `# Function tree — \`${root}\``,
    "",
    `${modules.length} module(s).`,
    "",
    "## Modules",
    "",
    "| Module | Classification | Fns | Edges out |",
    "| --- | --- | ---: | ---: |",
  ];
  for (const m of modules) {
    const c = countEdges(m);
    lines.push(
      `| [\`${m.path}\`](#${anchorFor(m.path)}) | ${classificationBadge(m.classification)} | ${m.functions.length} | ${c.out} |`
    );
  }
  lines.push("", "## Functions", "");
  for (const m of modules) {
    lines.push(`### \`${m.path}\` <a id="${anchorFor(m.path)}"></a>`);
    if (m.classification.length > 0) {
      lines.push("", `Classification: ${classificationBadge(m.classification)}`);
    }
    lines.push("");
    if (m.functions.length === 0) {
      lines.push("_No top-level functions detected._", "");
      continue;
    }
    for (const f of m.functions) {
      lines.push(fnHeading(f));
      const edges = edgeLines(f, reverse);
      if (edges.length === 0) {
        lines.push("", "_No tracked edges._", "");
      } else {
        lines.push("", ...edges, "");
      }
    }
  }
  return lines.join("\n");
}

function anchorFor(modulePath: string): string {
  return modulePath.replace(/[^a-zA-Z0-9]+/g, "-").toLowerCase();
}
