import { describe, it, expect } from "vitest";
import { renderMarkdown } from "./render-md.ts";
import type { FunctionTree } from "./types.ts";

function sampleTree(): FunctionTree {
  return {
    $schema: "function-tree/v1",
    generated_at: "2026-01-01T00:00:00Z",
    roots: ["src/lib", "src/server"],
    modules: [
      {
        path: "src/lib/util.ts",
        root: "src/lib",
        classification: [],
        functions: [
          {
            id: "src/lib/util.ts#formatCents",
            name: "formatCents",
            kind: "function",
            line: 1,
            exported: true,
            classification: [],
            edges: [{ kind: "calls", external: "zod" }],
            unresolved: 0,
          },
        ],
      },
      {
        path: "src/server/actions.ts",
        root: "src/server",
        classification: ["server-action"],
        functions: [
          {
            id: "src/server/actions.ts#doThing",
            name: "doThing",
            kind: "function",
            line: 5,
            exported: true,
            classification: ["server-action"],
            edges: [{ kind: "calls", target: "src/lib/util.ts#formatCents" }],
            unresolved: 2,
          },
        ],
      },
    ],
    reverse: {
      calls: { "src/lib/util.ts#formatCents": ["src/server/actions.ts#doThing"] },
      renders: {},
      new: {},
      "dynamic-import": {},
    },
  };
}

describe("renderMarkdown", () => {
  const out = renderMarkdown(sampleTree());

  it("produces index, modules, and one file per root", () => {
    expect(Object.keys(out).sort()).toEqual([
      "index.md",
      "modules.md",
      "src-lib.md",
      "src-server.md",
    ]);
  });

  it("renders the per-root file with reverse edges visible", () => {
    expect(out["src-lib.md"]).toContain("called by");
    expect(out["src-lib.md"]).toContain("src/server/actions.ts#doThing");
  });

  it("renders unresolved counter when non-zero", () => {
    expect(out["src-server.md"]).toContain("unresolved: 2");
  });

  it("renders classification badge on tagged modules", () => {
    expect(out["src-server.md"]).toContain("server-action");
  });

  it("renders the GENERATED header on every file", () => {
    for (const body of Object.values(out))
      expect(body.startsWith("<!-- Generated by scripts/function-tree")).toBe(true);
  });

  it("marks external edges as `[external] <pkg>` (not as a separate label)", () => {
    expect(out["src-lib.md"]).toContain("[external] zod");
    // Must not still emit the old `(external)` label.
    expect(out["src-lib.md"]).not.toContain("(external):");
  });
});
